export const ADMIN_BASE = '/admin' as const;
/** Must stay under ``ADMIN_BASE`` — Vite ``base`` is ``/admin/`` (SPA lives at ``/admin/``). */
export const SIDECAR_BASE = `${ADMIN_BASE}/sidecar` as const;

export const ROUTES = {
  home: '/' as const,
  products: '/products' as const,

  sidecar: {
    base: SIDECAR_BASE,
    home: `${SIDECAR_BASE}/home` as const,
    dropzone: `${SIDECAR_BASE}/dropzone` as const,
    meals: `${SIDECAR_BASE}/meals` as const,
    pets: `${SIDECAR_BASE}/pets` as const,
    profile: `${SIDECAR_BASE}/profile` as const,
  },

  admin: {
    base: ADMIN_BASE,
    login: `${ADMIN_BASE}/login` as const,
    dashboard: `${ADMIN_BASE}/dashboard` as const,
    zenDashboard: `${ADMIN_BASE}/zen-dashboard` as const,
    focus: `${ADMIN_BASE}/focus` as const,
    growthSystem: `${ADMIN_BASE}/growth-system` as const,
    personalBranding: `${ADMIN_BASE}/personal-branding` as const,
    personalBrandingBrandIdentity: `${ADMIN_BASE}/personal-branding/brand-identity` as const,
    personalBrandingWorkbench: `${ADMIN_BASE}/personal-branding/workbench` as const,
    personalBrandingPipeline: `${ADMIN_BASE}/personal-branding/pipeline` as const,
    personalBrandingRadar: `${ADMIN_BASE}/personal-branding/radar` as const,
    personalBrandingContentStream: `${ADMIN_BASE}/personal-branding/content-stream` as const,
    personalBrandingRolodex: `${ADMIN_BASE}/personal-branding/rolodex` as const,
    tasks: `${ADMIN_BASE}/tasks` as const,
    habits: `${ADMIN_BASE}/habits` as const,
    metrics: `${ADMIN_BASE}/metrics` as const,
    goals: `${ADMIN_BASE}/goals` as const,
    projects: `${ADMIN_BASE}/projects` as const,
    logbook: `${ADMIN_BASE}/logbook` as const,
    weeklyReview: `${ADMIN_BASE}/weekly-review` as const,
    planner: `${ADMIN_BASE}/planner` as const,
    plannerWeek: `${ADMIN_BASE}/planner/week` as const,
    plannerNightly: `${ADMIN_BASE}/planner/nightly` as const,
    healthFitness: `${ADMIN_BASE}/health-fitness` as const,
    healthFitnessNutrition: `${ADMIN_BASE}/health-fitness/nutrition` as const,
    healthFitnessWorkouts: `${ADMIN_BASE}/health-fitness/workouts` as const,
    healthFitnessAura: `${ADMIN_BASE}/health-fitness/aura` as const,
    healthFitnessRewards: `${ADMIN_BASE}/health-fitness/rewards` as const,
    assistant: `${ADMIN_BASE}/assistant` as const,
    assistantToolSafety: `${ADMIN_BASE}/assistant/settings` as const,
    assistantProactive: `${ADMIN_BASE}/assistant/proactive` as const,
    assistantInterventions: `${ADMIN_BASE}/assistant/interventions` as const,
    assistantObservability: `${ADMIN_BASE}/assistant/observability` as const,
    assistantSandbox: `${ADMIN_BASE}/assistant/sandbox` as const,
    memoryAudit: `${ADMIN_BASE}/memory-audit` as const,
    settings: `${ADMIN_BASE}/settings` as const,
    componentsDemo: `${ADMIN_BASE}/components-demo` as const,
    mediaBacklog: `${ADMIN_BASE}/media-backlog` as const,
    hobbyQuests: `${ADMIN_BASE}/hobby-quests` as const,
    rewardsStore: `${ADMIN_BASE}/rewards-store` as const,
    rewardStudio: `${ADMIN_BASE}/reward-studio` as const,
    knowledgeVault: `${ADMIN_BASE}/knowledge-vault` as const,
    knowledgeVaultLibrary: `${ADMIN_BASE}/knowledge-vault/library` as const,
    knowledgeVaultDocument: `${ADMIN_BASE}/knowledge-vault/documents/:documentId` as const,
    knowledgeVaultCourses: `${ADMIN_BASE}/knowledge-vault/courses` as const,
    knowledgeVaultSkillTree: `${ADMIN_BASE}/knowledge-vault/skill-tree` as const,
    knowledgeVaultFlashcards: `${ADMIN_BASE}/knowledge-vault/flashcards` as const,
    knowledgeVaultCollider: `${ADMIN_BASE}/knowledge-vault/collider` as const,
    knowledgeVaultInbox: `${ADMIN_BASE}/knowledge-vault/inbox` as const,
    knowledgeVaultCheatSheet: `${ADMIN_BASE}/knowledge-vault/cheat-sheet` as const,
    knowledgeVaultSyntopic: `${ADMIN_BASE}/knowledge-vault/syntopic` as const,
    knowledgeVaultProjectLabs: `${ADMIN_BASE}/knowledge-vault/project-labs` as const,
    knowledgeVaultTaskLinks: `${ADMIN_BASE}/knowledge-vault/task-links` as const,
    knowledgeVaultDailyLearning: `${ADMIN_BASE}/knowledge-vault/daily-learning` as const,
    knowledgeVaultFeynmanStudy: `${ADMIN_BASE}/knowledge-vault/study` as const,
    agencyArtifacts: `${ADMIN_BASE}/agency-artifacts` as const,
    tools: {
      base: `${ADMIN_BASE}/tools` as const,
      workflows: `${ADMIN_BASE}/tools/workflows` as const,
      workflowEditor: `${ADMIN_BASE}/tools/workflows/:workflowId` as const,
      cronBuilder: `${ADMIN_BASE}/tools/cron-builder` as const,
      postman: `${ADMIN_BASE}/tools/postman` as const,
      webhooks: `${ADMIN_BASE}/tools/webhooks` as const,
      webhookDetail: `${ADMIN_BASE}/tools/webhooks/:catcherId` as const,
      whiteboard: `${ADMIN_BASE}/tools/whiteboard` as const,
      whiteboardFile: `${ADMIN_BASE}/tools/whiteboard/:boardId` as const,
      formatters: `${ADMIN_BASE}/tools/formatters` as const,
      jwt: `${ADMIN_BASE}/tools/jwt` as const,
      base64: `${ADMIN_BASE}/tools/base64` as const,
      regex: `${ADMIN_BASE}/tools/regex` as const,
      docker: `${ADMIN_BASE}/tools/docker` as const,
      eslint: `${ADMIN_BASE}/tools/eslint` as const,
    },
    markdownViewer: `${ADMIN_BASE}/markdown-viewer` as const,
    markdownViewerFile: `${ADMIN_BASE}/markdown-viewer/:filePath` as const,
    /** Career hub + resume tooling (requires backend Postgres DATABASE_URL). */
    careerDevelopment: `${ADMIN_BASE}/career` as const,
    careerResume: `${ADMIN_BASE}/career/resume` as const,
    careerJobSources: `${ADMIN_BASE}/career/job-sources` as const,
    /** Leisure-only travel lounge (route access gated — see LeisureOnlyRoute). */
    voyager: `${ADMIN_BASE}/voyager` as const,
    voyagerTrips: `${ADMIN_BASE}/voyager/trips` as const,
    voyagerMilestones: `${ADMIN_BASE}/voyager/milestones` as const,
    voyagerItinerary: `${ADMIN_BASE}/voyager/itinerary` as const,
  },
} as const;

/** Normalize trailing slashes so route checks match `/admin/login` and `/admin/login/`. */
export function isAdminLoginPath(pathname: string): boolean {
  const p = pathname.replace(/\/+$/, '') || '/';
  return p === ROUTES.admin.login;
}

export const ADMIN_CHILD_ROUTES = {
  dashboard: 'dashboard' as const,
  zenDashboard: 'zen-dashboard' as const,
  focus: 'focus' as const,
  growthSystem: 'growth-system' as const,
  personalBranding: 'personal-branding' as const,
  tasks: 'tasks' as const,
  habits: 'habits' as const,
  metrics: 'metrics' as const,
  goals: 'goals' as const,
  projects: 'projects' as const,
  logbook: 'logbook' as const,
  weeklyReview: 'weekly-review' as const,
  planner: 'planner' as const,
  plannerWeek: 'planner/week' as const,
  plannerNightly: 'planner/nightly' as const,
  healthFitness: 'health-fitness' as const,
  healthFitnessNutrition: 'health-fitness/nutrition' as const,
  healthFitnessWorkouts: 'health-fitness/workouts' as const,
  healthFitnessAura: 'health-fitness/aura' as const,
  healthFitnessRewards: 'health-fitness/rewards' as const,
  assistant: 'assistant' as const,
  assistantToolSafety: 'assistant/settings' as const,
  assistantProactive: 'assistant/proactive' as const,
  assistantInterventions: 'assistant/interventions' as const,
  assistantObservability: 'assistant/observability' as const,
  assistantSandbox: 'assistant/sandbox' as const,
  memoryAudit: 'memory-audit' as const,
  settings: 'settings' as const,
  componentsDemo: 'components-demo' as const,
  mediaBacklog: 'media-backlog' as const,
  hobbyQuests: 'hobby-quests' as const,
  rewardsStore: 'rewards-store' as const,
  rewardStudio: 'reward-studio' as const,
  knowledgeVault: 'knowledge-vault' as const,
  knowledgeVaultLibrary: 'knowledge-vault/library' as const,
  knowledgeVaultDocument: 'knowledge-vault/documents/:documentId' as const,
  knowledgeVaultCourses: 'knowledge-vault/courses' as const,
  knowledgeVaultSkillTree: 'knowledge-vault/skill-tree' as const,
  knowledgeVaultFlashcards: 'knowledge-vault/flashcards' as const,
  knowledgeVaultCollider: 'knowledge-vault/collider' as const,
  knowledgeVaultInbox: 'knowledge-vault/inbox' as const,
  knowledgeVaultCheatSheet: 'knowledge-vault/cheat-sheet' as const,
  knowledgeVaultSyntopic: 'knowledge-vault/syntopic' as const,
  knowledgeVaultProjectLabs: 'knowledge-vault/project-labs' as const,
  knowledgeVaultTaskLinks: 'knowledge-vault/task-links' as const,
  knowledgeVaultDailyLearning: 'knowledge-vault/daily-learning' as const,
  knowledgeVaultFeynmanStudy: 'knowledge-vault/study' as const,
  agencyArtifacts: 'agency-artifacts' as const,
  tools: 'tools' as const,
  /** Relative segments under parent Route path="tools" */
  toolsWorkflows: 'workflows' as const,
  toolsWorkflowEditor: 'workflows/:workflowId' as const,
  toolsCronBuilder: 'cron-builder' as const,
  toolsPostman: 'postman' as const,
  toolsWebhooks: 'webhooks' as const,
  toolsWebhookDetail: 'webhooks/:catcherId' as const,
  toolsWhiteboard: 'whiteboard' as const,
  toolsWhiteboardFile: 'whiteboard/:boardId' as const,
  toolsFormatters: 'formatters' as const,
  toolsJwt: 'jwt' as const,
  toolsBase64: 'base64' as const,
  toolsRegex: 'regex' as const,
  toolsDocker: 'docker' as const,
  toolsEslint: 'eslint' as const,
  markdownViewer: 'markdown-viewer' as const,
  markdownViewerFile: 'markdown-viewer/:filePath' as const,
  voyager: 'voyager' as const,
  career: 'career' as const,
} as const;
