export const ADMIN_BASE = '/admin' as const;

export const ROUTES = {
  home: '/' as const,
  products: '/products' as const,

  admin: {
    base: ADMIN_BASE,
    login: `${ADMIN_BASE}/login` as const,
    dashboard: `${ADMIN_BASE}/dashboard` as const,
    zenDashboard: `${ADMIN_BASE}/zen-dashboard` as const,
    focus: `${ADMIN_BASE}/focus` as const,
    growthSystem: `${ADMIN_BASE}/growth-system` as const,
    tasks: `${ADMIN_BASE}/tasks` as const,
    habits: `${ADMIN_BASE}/habits` as const,
    metrics: `${ADMIN_BASE}/metrics` as const,
    goals: `${ADMIN_BASE}/goals` as const,
    projects: `${ADMIN_BASE}/projects` as const,
    logbook: `${ADMIN_BASE}/logbook` as const,
    weeklyReview: `${ADMIN_BASE}/weekly-review` as const,
    assistant: `${ADMIN_BASE}/assistant` as const,
    assistantToolSafety: `${ADMIN_BASE}/assistant/settings` as const,
    assistantProactive: `${ADMIN_BASE}/assistant/proactive` as const,
    memoryAudit: `${ADMIN_BASE}/memory-audit` as const,
    settings: `${ADMIN_BASE}/settings` as const,
    componentsDemo: `${ADMIN_BASE}/components-demo` as const,
    mediaBacklog: `${ADMIN_BASE}/media-backlog` as const,
    hobbyQuests: `${ADMIN_BASE}/hobby-quests` as const,
    rewardsStore: `${ADMIN_BASE}/rewards-store` as const,
    rewardStudio: `${ADMIN_BASE}/reward-studio` as const,
    knowledgeVault: `${ADMIN_BASE}/knowledge-vault` as const,
    knowledgeVaultLibrary: `${ADMIN_BASE}/knowledge-vault/library` as const,
    knowledgeVaultCourses: `${ADMIN_BASE}/knowledge-vault/courses` as const,
    knowledgeVaultSkillTree: `${ADMIN_BASE}/knowledge-vault/skill-tree` as const,
    knowledgeVaultFlashcards: `${ADMIN_BASE}/knowledge-vault/flashcards` as const,
    knowledgeVaultCollider: `${ADMIN_BASE}/knowledge-vault/collider` as const,
    knowledgeVaultInbox: `${ADMIN_BASE}/knowledge-vault/inbox` as const,
    knowledgeVaultMindPalace: `${ADMIN_BASE}/knowledge-vault/mind-palace` as const,
    knowledgeVaultCheatSheet: `${ADMIN_BASE}/knowledge-vault/cheat-sheet` as const,
    knowledgeVaultSyntopic: `${ADMIN_BASE}/knowledge-vault/syntopic` as const,
    knowledgeVaultTaskLinks: `${ADMIN_BASE}/knowledge-vault/task-links` as const,
    knowledgeVaultFeynmanStudy: `${ADMIN_BASE}/knowledge-vault/study` as const,
    tools: `${ADMIN_BASE}/tools` as const,
    markdownViewer: `${ADMIN_BASE}/markdown-viewer` as const,
    markdownViewerFile: `${ADMIN_BASE}/markdown-viewer/:filePath` as const,
  },
} as const;

/** Normalize trailing slashes so route checks match `/admin/login` and `/admin/login/`. */
export function isAdminLoginPath(pathname: string): boolean {
  const p = pathname.replace(/\/+$/, '') || '/';
  return p === ROUTES.admin.login;
}

export const ADMIN_CHILD_ROUTES = {
  dashboard: 'dashboard' as const,
  zenDashboard: 'zen-dashboard' as const,
  focus: 'focus' as const,
  growthSystem: 'growth-system' as const,
  tasks: 'tasks' as const,
  habits: 'habits' as const,
  metrics: 'metrics' as const,
  goals: 'goals' as const,
  projects: 'projects' as const,
  logbook: 'logbook' as const,
  weeklyReview: 'weekly-review' as const,
  assistant: 'assistant' as const,
  assistantToolSafety: 'assistant/settings' as const,
  assistantProactive: 'assistant/proactive' as const,
  memoryAudit: 'memory-audit' as const,
  settings: 'settings' as const,
  componentsDemo: 'components-demo' as const,
  mediaBacklog: 'media-backlog' as const,
  hobbyQuests: 'hobby-quests' as const,
  rewardsStore: 'rewards-store' as const,
  rewardStudio: 'reward-studio' as const,
  knowledgeVault: 'knowledge-vault' as const,
  knowledgeVaultLibrary: 'knowledge-vault/library' as const,
  knowledgeVaultCourses: 'knowledge-vault/courses' as const,
  knowledgeVaultSkillTree: 'knowledge-vault/skill-tree' as const,
  knowledgeVaultFlashcards: 'knowledge-vault/flashcards' as const,
  knowledgeVaultCollider: 'knowledge-vault/collider' as const,
  knowledgeVaultInbox: 'knowledge-vault/inbox' as const,
  knowledgeVaultMindPalace: 'knowledge-vault/mind-palace' as const,
  knowledgeVaultCheatSheet: 'knowledge-vault/cheat-sheet' as const,
  knowledgeVaultSyntopic: 'knowledge-vault/syntopic' as const,
  knowledgeVaultTaskLinks: 'knowledge-vault/task-links' as const,
  knowledgeVaultFeynmanStudy: 'knowledge-vault/study' as const,
  tools: 'tools' as const,
  markdownViewer: 'markdown-viewer' as const,
  markdownViewerFile: 'markdown-viewer/:filePath' as const,
} as const;
